server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: zh15107551311
    url: jdbc:mysql://localhost:3306/registerUser?useSSL=false&serverTimezone=UTC
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

