server:
  port: 8001

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: zh15107551311
    url: jdbc:mysql://localhost:3306/registerUser?useSSL=false&serverTimezone=UTC
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

